# -*- coding: utf-8 -*-
from marshmallow import Schema, fields
from sippers.utils import TABLA_6, TABLA_9, TABLA_12, TABLA_3, TABLA_17, TABLA_26, TABLA_30, TABLA_32, TABLA_35, TABLA_62, TABLA_64, TABLA_108, TABLA_111
from marshmallow.validate import OneOf


class CnmcV3SipsSchema(Schema):
    """Base model for SIPS
    """
    cnae = fields.String(allow_none=True)
    aplicacionBonoSocial = fields.String(allow_none=True)
    codigoAPM = fields.String(allow_none=True)
    codigoAccesibilidadContador = fields.String(allow_none=True)
    codigoBIE = fields.String(allow_none=True)
    codigoClaseExpediente = fields.String(allow_none=True)
    codigoClasificacionPS = fields.String(validate=OneOf(TABLA_30), allow_none=True)
    codigoDHEquipoDeMedida = fields.String(validate=OneOf(TABLA_35), allow_none=True)
    codigoEmpresaDistribuidora = fields.String(allow_none=True)
    codigoFasesEquipoMedida = fields.String(allow_none=True)
    codigoModoControlPotencia = fields.String(allow_none=True)
    codigoMotivoExpediente = fields.String(allow_none=True)
    codigoPSContratable = fields.String(allow_none=True)
    codigoPeriodicidadFacturacion = fields.String(validate=OneOf(TABLA_108), allow_none=True)
    codigoPostalPS = fields.String(allow_none=True)
    codigoPropiedadEquipoMedida = fields.String(validate=OneOf(TABLA_32), allow_none=True)
    codigoPropiedadICP = fields.String(validate=OneOf(TABLA_32), allow_none=True)
    codigoProvinciaPS = fields.String(allow_none=True)
    codigoTarifaATREnVigor = fields.String(validate=OneOf(TABLA_17), allow_none=True)
    codigoTensionMedida = fields.String(validate=OneOf(TABLA_64), allow_none=True)
    codigoTensionV = fields.String(validate=OneOf(TABLA_64), allow_none=True)
    codigoTipoContrato = fields.String(validate=OneOf(TABLA_9), allow_none=True)
    codigoTipoSuministro = fields.String(validate=OneOf(TABLA_62), allow_none=True)
    cups = fields.String(required=True, allow_none=False)
    esViviendaHabitual = fields.String(validate=OneOf(TABLA_26) ,allow_none=True)
    fechaAltaSuministro = fields.DateTime(allow_none=True)
    fechaCaducidadAPM = fields.DateTime(allow_none=True)
    fechaCaducidadBIE = fields.DateTime(allow_none=True)
    fechaEmisionAPM = fields.DateTime(allow_none=True)
    fechaEmisionBIE = fields.DateTime(allow_none=True)
    fechaLimiteDerechosReconocidos = fields.DateTime(allow_none=True)
    fechaUltimaLectura = fields.DateTime(allow_none=True)
    fechaUltimoCambioComercializador = fields.DateTime(allow_none=True)
    fechaUltimoMovimientoContrato = fields.DateTime(allow_none=True)
    motivoEstadoNoContratable = fields.String(allow_none=True)
    nombreEmpresaDistribuidora = fields.String(allow_none=True)
    potenciaCGPW = fields.String(allow_none=True)
    potenciaMaximaAPMW = fields.String(allow_none=True)
    potenciaMaximaBIEW = fields.String(allow_none=True)
    potenciasContratadasEnWP1 = fields.String(allow_none=True)
    potenciasContratadasEnWP2 = fields.String(allow_none=True)
    potenciasContratadasEnWP3 = fields.String(allow_none=True)
    potenciasContratadasEnWP4 = fields.String(allow_none=True)
    potenciasContratadasEnWP5 = fields.String(allow_none=True)
    potenciasContratadasEnWP6 = fields.String(allow_none=True)
    relacionTransformacionIntensidad = fields.String(allow_none=True)
    tipoIdTitular = fields.String(validate=OneOf(TABLA_6), allow_none=True)
    tipoPerfilConsumo = fields.String(allow_none=True)
    valorDerechosAccesoW = fields.String(allow_none=True)
    valorDerechosExtensionW = fields.String(allow_none=True)
    referenciaCatastralPS = fields.String(allow_none=True)
    XPS = fields.String(allow_none=True)
    YPS = fields.String(allow_none=True)
    HusoPS = fields.String(allow_none=True)
    BandaPS = fields.String(allow_none=True)
    PaisPS = fields.String(allow_none=True)
    desProvinciaPS = fields.String(allow_none=True)
    codigoMunicipioPS
    desMunicipioPS = fields.String(allow_none=True)
    PoblacionPS = fields.String(allow_none=True)
    desPoblacionPS = fields.String(allow_none=True)
    tipoViaPS = fields.String(validate=OneOf(TABLA_12), allow_none=True)
    viaPS = fields.String(allow_none=True)
    numFincaPS = fields.String(allow_none=True)
    duplicadorFincaPS = fields.String(allow_none=True)
    escaleraPS = fields.String(allow_none=True)
    pisoPS = fields.String(allow_none=True)
    puertaPS = fields.String(allow_none=True)
    tipoAclaradorFincaPS = fields.String(allow_none=True)
    aclaradorFincaPS = fields.String(allow_none=True)
    codigoSegmentoCargoEnVigor = fields.String(allow_none=True)
    tipoControDelPotencia = fields.String(allow_none=True)
    cambioComercializadorEnCurso = fields.String(validate=OneOf(TABLA_3), allow_none=True)
    codigoComercializadorVigente  = fields.String(allow_none=True)
    fechaUltimoCambioAgregadorIndependiente  = fields.DateTime(allow_none=True)
    cambioAgregadorIndependienteEnCurso  = fields.String(validate=OneOf(TABLA_3), allow_none=True)
    codigoAgregadorIndependienteVigente  = fields.String(allow_none=True)
    suspensionSuminstroImpago = fields.String(validate=OneOf(TABLA_26), allow_none=True)
    tipoPersona  = fields.String(validate=OneOf(TABLA_115), allow_none=True)
    idTitular = fields.String(allow_none=True)
    nombreTitular = fields.String(allow_none=True)
    apellido1Titular = fields.String(allow_none=True)
    apellido2Titular = fields.String(allow_none=True)
    PaisTitular = fields.String(allow_none=True)
    codigoProvinciaTitular = fields.String(allow_none=True)
    desProvinciaTitular = fields.String(allow_none=True)
    codigoMunicipioTitular = fields.String(allow_none=True)
    desMunicipioTitular = fields.String(allow_none=True)
    PoblacionTitular = fields.String(allow_none=True)
    desPoblacionTitular = fields.String(allow_none=True)
    codigoPostalTitular = fields.String(allow_none=True)
    tipoViaTitular = fields.String(validate=OneOf(TABLA_12), allow_none=True)
    viaTitular = fields.String(allow_none=True)
    numFincaTitular = fields.String(allow_none=True)
    duplicadorFincaTitular = fields.String(allow_none=True)
    escaleraTitular = fields.String(allow_none=True)
    pisoTitular = fields.String(allow_none=True)
    puertaTitular = fields.String(allow_none=True)
    tipoAclaradorFincaTitular = fields.String(allow_none=True)
    aclaradorFincaTitular = fields.String(allow_none=True)
    codigoLecturaRemota = fields.String(allow_none=True)
    acogimientoAutoconsumo = fields.String(validate=OneOf(TABLA_26) ,allow_none=True)
    suministroEsencial = fields.String(validate=OneOf(TABLA_26) ,allow_none=True)

class CnmcV3MeasuresSchema(Schema):

    cups = fields.String(position=0, required=True, allow_none=False)
    codigoDHEquipoDeMedida = fields.String(position=28, allow_none=True)
    codigoTarifaATR = fields.String(position=3, allow_none=True)
    codigoTipoLectura = fields.String(position=29, allow_none=True)
    consumoEnergiaActivaEnWhP1 = fields.String(position=4)
    consumoEnergiaActivaEnWhP2 = fields.String(position=5)
    consumoEnergiaActivaEnWhP3 = fields.String(position=6)
    consumoEnergiaActivaEnWhP4 = fields.String(position=7)
    consumoEnergiaActivaEnWhP5 = fields.String(position=8)
    consumoEnergiaActivaEnWhP6 = fields.String(position=9)
    consumoEnergíaReactivaInductivaEnVArhP1 = fields.String(position=10)
    consumoEnergíaReactivaInductivaEnVArhP2 = fields.String(position=11)
    consumoEnergíaReactivaInductivaEnVArhP3 = fields.String(position=12)
    consumoEnergíaReactivaInductivaEnVArhP4 = fields.String(position=13)
    consumoEnergíaReactivaInductivaEnVArhP5 = fields.String(position=14)
    consumoEnergíaReactivaInductivaEnVArhP6 = fields.String(position=15)
    consumoEnergíaReactivaCapacitivaEnVArhP1 = fields.String(position=16)
    consumoEnergíaReactivaCapacitivaEnVArhP2 = fields.String(position=17)
    consumoEnergíaReactivaCapacitivaEnVArhP3 = fields.String(position=18)
    consumoEnergíaReactivaCapacitivaEnVArhP4 = fields.String(position=19)
    consumoEnergíaReactivaCapacitivaEnVArhP5 = fields.String(position=20)
    consumoEnergíaReactivaCapacitivaEnVArhP6 = fields.String(position=21)
    fechaFinMesConsumo = fields.DateTime(required=True, position=2, allow_none=False)
    fechaInicioMesConsumo = fields.DateTime(required=True, position=1, allow_none=False)
    potenciaDemandadaEnWP1 = fields.String(position=22)
    potenciaDemandadaEnWP2 = fields.String(position=23)
    potenciaDemandadaEnWP3 = fields.String(position=24)
    potenciaDemandadaEnWP4 = fields.String(position=25)
    potenciaDemandadaEnWP5 = fields.String(position=26)
    potenciaDemandadaEnWP6 = fields.String(position=27)
