from marshmallow import Schema, fields


class EndesaSipsSchema(Schema):
    name = fields.String(position=0)
    distri = fields.String(position=1)
    cod_distri = fields.String(position=2)
    direccio = fields.String(position=3)
    poblacio = fields.String(position=4)
    codi_postal = fields.String(position=5)
    provincia = fields.String(position=6)
    data_alta = fields.String(position=7)
    tarifa = fields.String(position=8)
    des_tarifa = fields.String(position=9)
    tensio = fields.String(position=10)
    pot_max_bie = fields.String(position=11)
    pot_max_puesta = fields.String(position=12)
    tipo_pm = fields.String(position=13)
    indicatiu_icp = fields.String(position=14)
    perfil_consum = fields.String(position=15)
    der_extensio = fields.String(position=16)
    der_acces_llano = fields.String(position=17)
    der_acces_valle = fields.String(position=18)
    propietat_equip_mesura = fields.String(position=19)
    propietat_icp = fields.String(position=20)
    pot_cont_p1 = fields.String(position=21)
    pot_cont_p2 = fields.String(position=22)
    pot_cont_p3 = fields.String(position=23)
    pot_cont_p4 = fields.String(position=24)
    pot_cont_p5 = fields.String(position=25)
    pot_cont_p6 = fields.String(position=26)
    data_ulti_mov = fields.String(position=27)
    data_ult_canv = fields.String(position=28)
    data_lim_exten = fields.String(position=29)
    data_ult_lect = fields.String(position=30)
    talls = fields.String(position=31)
    fianza = fields.String(position=32)
    persona_fj = fields.String(position=33)
    nom = fields.String(position=34)
    cognom = fields.String(position=35)
    direccio_titular = fields.String(position=36)
    municipi_titular = fields.String(position=37)
    codi_postal_titular = fields.String(position=38)
    provincia_titular = fields.String(position=39)
    primera_vivenda = fields.String(position=40)
    facturacio = fields.String(position=41)
    salt = fields.String(position=42)