# -*- coding: utf-8 -*-
from marshmallow import Schema, fields


class HidrocantabricoSchema(Schema):
    punto_de_suministro = fields.String(description="Punto de suministro", position=0, length=10)
    name = fields.String(description="CUPS", position=1, length=22)
    distri = fields.String(description="Empresa distribuidora", position=2, length=54)
    poblacio = fields.String(description="Ubicación PS", position=3, length=81)
    codi_postal = fields.String(description="Población_Codigo PS", position=4, length=14)
    provincia = fields.String(description="Provincia", position=5, length=2)
    data_alta = fields.String(description="Fecha de alta", position=6, length=8)
    tarifa = fields.String(description="Tarifa en vigor", position=7, length=5)
    tensio = fields.String(description="Tensión", position=8, length=10)
    pot_max_bie = fields.String(description="Potencia Máxima Boletín", position=9, length=10)
    pot_max_puesta = fields.String(description="Potencia Máxima APM", position=10, length=10)
    tipo_pm = fields.String(description="Tipo Punto Medida", position=11, length=2)
    indicatiu_icp = fields.String(description="Disponibilidad ICP", position=12, length=1)
    perfil_consum = fields.String(description="Tipo Perfil Consumo", position=13, length=1)
    der_extensio = fields.String(description="Derechos Extensión", position=14, length=10)
    der_acces_llano = fields.String(description="Derechos Acceso", position=15, length=10)
    propietat_equip_mesura = fields.String(description="Propiedad Equipo Medida", position=16, length=1)
    propietat_icp = fields.String(description="Propiedad ICP", position=17, length=1)
    pot_cont_p1 = fields.String(description="Potencias Contratada 1", position=18, length=10)
    pot_cont_p2 = fields.String(description="Potencias Contratada 2", position=19, length=10)
    pot_cont_p3 = fields.String(description="Potencias Contratada 3", position=20, length=10)
    pot_cont_p4 = fields.String(description="Potencias Contratada 4", position=21, length=10)
    pot_cont_p5 = fields.String(description="Potencias Contratada 5", position=22, length=10)
    pot_cont_p6 = fields.String(description="Potencias Contratada 6", position=23, length=10)
    potencias_contratada_7 = fields.String(description="Potencias Contratada 7", position=24, length=10)
    data_ulti_mov = fields.String(description="Fecha Ultimo Movimiento de Contratacion", position=25, length=8)
    data_ult_canv = fields.String(description="Fecha Ultimo Cambio de Comercializador", position=26, length=8)
    data_lim_exten = fields.String(description="Fecha límite derechos extensión", position=27, length=8)
    fecha_ultima_lectura = fields.String(description="Fecha ultima lectura", position=28, length=8)
    persona_fj = fields.String(description="Tipo de interlocutor", position=29, length=1)
    nombre_ic = fields.String(description="Nombre IC", position=30, length=80)
    ubicacion_ic = fields.String(description="Ubicación IC", position=31, length=81)
    poblacion_ic = fields.String(description="Población IC", position=32, length=12)
    codigo_postal = fields.String(description="Código postal", position=33, length=10)
    provincia_ = fields.String(description="Provincia", position=34, length=3)
    primera_vivenda = fields.String(description="vivienda habitual", position=35, length=1)
    fianza = fields.String(description="Depósito garantía", position=36, length=13)
    deuda = fields.String(description="Deuda", position=37, length=1)
